services:
  patient-service-db:
    container_name: patient-service-db
    image: postgres:latest
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    networks:
      - internal
    volumes:
      - pgdata:/var/lib/postgresql/data

  patient-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: patient-service:latest
    container_name: patient-service-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    ports:
      - "4000:4000"
    depends_on:
      - patient-service-db
    networks:
      - internal

volumes:
  pgdata:

networks:
  internal:
    name: internal
    driver: bridge
